workflow:
  name: Solar System Nodejs App
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' || $CI_COMMIT_BRANCH =~ /^feature/
      when: always
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^feature/ && $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always

stages:
  - test

unit_tests:
    stage: test
    image: node:18-alpine3.17
    before_script:
        - npm install
    script:
        - npm test