name: solar system workflow

on: 
  workflow_dispatch:   
  push: 
    branches: 
    - main
    - freatures/* 
env: 
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}       
jobs: 
  unit-testing: 
    runs-on: ubuntu-latest
    steps: 
    - name: checkout the repo 
      uses: actions/checkout@v4 
    - name: get nodejs package 
      uses: actions/setup-node@v3
      with: 
        node-version: 18 
    - name: install npm dependencies 
      run: npm install 
    - name: run test 
      run: npm test             

    